version: "3.9"

volumes:
  _postgres_data:
   
services:
  db:
    image: postgres:12.6
    container_name: tim_db
    volumes:
      - _postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5432:5432"
  web:
    build: .
    container_name: web
    command: python manage.py runserver 0.0.0.0:80
    volumes:
      - .:/code
    ports:
      - "80:80"
    env_file:
      - .env
    depends_on:
      - db
      