version: "3.9"

volumes:
  _postgres_data:
   
services:
  db:
    image: postgres:13
    container_name: db
    volumes:
      - _postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5432:5432"
  migrations:
    build: .
    container_name: migrations
    profiles:
      - migrations
    command: python manage.py migrate
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - db
  web:
    build: .
    container_name: web
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - db
  nginx:
    container_name: nginx
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ~/projects/timo-frontend/dist:/var/www/
    depends_on:
      - web
      - db
